### ISSUE TITLE
DOC: typo?

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/dsp#1]
Should `saddle_innder(Fx, Gy)` be `saddle_inner(Fx, Gy)`?

**Comment by stephenpboyd** [comment]
Yes!

**Comment by phschiele** [comment]
Thanks again, @keithbriggs! Also fixed via [7d36c92](https://github.com/cvxgrp/dsp/commit/7d36c928b4c8919b231fe8d25190fa165cea9b96).
