### ISSUE TITLE
Naming convention?

### ISSUE THREAD

**Issue by tschm** [cvxgrp/dsp#12]
I think it would be helpful to have all cvxpy related packages in a cvx namespace. E.g. you would introduce a folder cvx (without __init__.py) and in there you would the dsp package. This would avoid collision if you work in projects with multiple cvx related packages. I do this for example in cvxmarkowitz or in the cvxrisk also in the simulator package. cvx is always the route of the source folders. Having a name like cvx.. makes it also nice when you poetry show (or similar)... @phschiele @PTNobel

**Comment by phschiele** [comment]
Good idea, @tschm, thank you. For now, most uses likely would either just work on cvxpy or install it via pip.
That said, I am happy to introduce this naming convention if we agree to do it across the complete ecosystem!
Closing for now, we can reopen once/if that is the case.
