### ISSUE TITLE
atom_canonicalizers renamed in cvxpy

### ISSUE THREAD

**Issue by rjboczar** [cvxgrp/dsp#18]
https://github.com/cvxpy/cvxpy/pull/2007

`cvxpy_integration.py` currently throws

`ModuleNotFoundError: No module named 'cvxpy.reductions.dcp2cone.atom_canonicalizers'`

when used with cvxpy 1.4.

**Comment by phschiele** [comment]
Thanks for the report @rjboczar! We just fixed this in the main branch, creating a new pip release shortly!
