### ISSUE TITLE
DOC: a word is missing

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/dsp#2]
"Saddle functions can scaled ..."

**Comment by stephenpboyd** [comment]
Thanks Keith for catching that!  We’ll update it soon.  Let us know if you find any other typos.

**Comment by phschiele** [comment]
Thanks @keithbriggs! Fixed via [7d36c92](https://github.com/cvxgrp/dsp/commit/7d36c928b4c8919b231fe8d25190fa165cea9b96).
